name: Report Report form for Sheller 
description: File a bug on Sheller using a easy to use form
title: "[Bug]:"
labels: ["bug"]
assignees:
  - guttih
body:
- type: markdown
  attributes:
    value: |
      Bug report on the Sheller - Visual Studio Code Extension
- type: input
  id: contact
  attributes:
    label: Contact Details
    description: How can I get in touch with you if I need more info?
    placeholder: ex. email@example.com
  validations:
    required: false
- type: textarea
  id: what-happened
  attributes:
    label: What happened?
    description: Also tell me, what did you expect to happen?
    placeholder: asdfasdf 

    value: | 
      ### Summary
      _Short summary of what is going on or to provide context_.

      <!-- Not required, but ment to help you along with writing a better bug report! -->
      ### Steps To Reproduce:
      1.  First I...
      2.  Then...
      ### Expected result
      _Describe what should have happened_.
  validations:
    required: true
- type: dropdown
  id: version
  attributes:
    label: Version - Sheller Extension
    description:  In VS Code select "View" > "Extensions", then type sheller and select the matching version here
    options:
      - 1.2.*
      - 1.2.15
      - 1.2.14
      - 1.2.13
      - 1.2.12
      - 1.2.11
      - 1.2.10
      - 1.2.9
      - 1.2.8
      - 1.2.7
      - 1.2.6
      - 1.2.5
      - 1.2.4
      - 1.2.3
      - 1.2.2
      - 1.2.1
      - 1.2.0
      - 1.1.3
      - 1.1.2
      - 1.1.1
      - 1.0.0
  validations:
    required: true
- type: textarea
  attributes:
    label: Version - Visual studio Code 
    description: In VS Code select "Help" > "About", then click on "Copy" and paste the text here
  validations:
    required: false
- type: dropdown
  id: os
  validations:
    required: true
  attributes:
    label: What operating system  are you seeing the problem on?
    multiple: true
    options:
      - Windows
      - Mac OS
      - Mac OS X
      - Linux - Red hat
      - Linux - Fedora/Centos/Rocky linux
      - Linux - Ubuntu
      - Linux - other
- type: input
  id: os_other
  attributes:
    label: Other operating system(s)
    description: Operating system(s) not in the options above can be added here
    placeholder: Other OS
- type: textarea
  id: notes
  attributes:
    label: Notes / Anything else? 
    description: Is there something else?  Something you want to add?  Please do, I would appreciate it :)
    render: shell
      
     
