name: Bug report
description: File a bug on Sheller
title: "[Bug]:"
labels: ["bug"]
assignees:
  - guttih
body:
- type: markdown
  attributes:
    value: |
      Bug report on the Sheller - Visual Studio Code Extension
- type: input
  id: contact
  attributes:
    label: Contact Details
    description: How can I get in touch with you if I need more info?
    placeholder: ex. email@example.com
  validations:
    required: false
- type: input
  id: summary
  attributes:
    label: Summary
    description: Short summary of what is going on or to provide context
  validations:
    required: false
- type: textarea
  id: what-happened
  attributes:
    label: What happened?    
    description: | 
      - **Additional context** Add any other context or screenshots about the bug here.
    placeholder: |
     Please write your bug report here 
    value: 
  validations:
    required: true
- type: textarea
  id: reproduce
  attributes:
    label: Steps To Reproduce
    description: |
      1.  First I...
      2.  Then...
      
      - **Additional context** Add any other context or screenshots about the bug here.
      
    placeholder: |
     Please describe to me how I can reproduce the bug, so I can find out how to fix it 
    value: 
  validations:
    required: false
- type: textarea
  id: expectedx
  attributes:
    label: Expected result
    description: |
      Describe what should have happened
        - **Additional context** Add any other context or screenshots about the bug here.
     
    placeholder:  |
     Please write your request here
    value: 
  validations:
    required: false
- type: dropdown
  id: version
  attributes:
    label: Version - Sheller Extension
    description:  In VS Code select "View" > "Extensions", then type sheller and select the matching version here
    options:
      - 1.2.*
      - 1.2.15
      - 1.2.14
      - 1.2.13
      - 1.2.12
      - 1.2.11
      - 1.2.10
      - 1.2.9
      - 1.2.8
      - 1.2.7
      - 1.2.6
      - 1.2.5
      - 1.2.4
      - 1.2.3
      - 1.2.2
      - 1.2.1
      - 1.2.0
      - 1.1.3
      - 1.1.2
      - 1.1.1
      - 1.0.0
  validations:
    required: true
- type: textarea
  attributes:
    label: Version - Visual studio Code 
    description: In VS Code select "Help" > "About", then click on "Copy" and paste the text here
    placeholder: |
      --- Version info will look something like this ---
      Version: 1.68.1
      Commit: 30d9c6cd9483b2cc586687151bcbcd635f373630
      Date: 2022-06-15T02:58:26.441Z
      Electron: 17.4.7
      Chromium: 98.0.4758.141
      Node.js: 16.13.0
      V8: 9.8.177.13-electron.0
      OS: Linux x64 4.18.0-348.23.1.el8_5.x86_64
  validations:
    required: false
- type: dropdown
  id: os
  validations:
    required: true
  attributes:
    label: What operating system  are you seeing the problem on?
    multiple: true
    options:
      - Windows
      - Mac OS
      - Mac OS X
      - Linux - Red hat
      - Linux - Fedora/Centos/Rocky linux
      - Linux - Ubuntu
      - Linux - other
      - Other
- type: input
  id: os_other
  attributes:
    label: Other operating system(s)
    description: Operating system(s) not in the options above can be added here
    placeholder: Other OS
- type: textarea
  id: notes
  attributes:
    label: Notes
    description: Is there something else? 
    placeholder: | 
                  Something you want to add?  
                  Please do, I would appreciate it :)
    render: shell
