name: Feature request
description: Suggest an idea for the Sheller extension
title: "[Feature]:"
labels: ["enhancement"]
assignees:
  - guttih
body:
- type: markdown
  attributes:
    value: |
      Feature request on the Sheller - Visual Studio Code Extension
- type: input
  id: contact
  attributes:
    label: Contact Details
    description: How can I get in touch with you if I need more info?
    placeholder: ex. email@example.com
  validations:
    required: false
- type: textarea
  id: why
  attributes:
    label: Why do you want this feature?
    description: Also tell me, what did you expect to happen?
    placeholder:  |
     Ideas to help you along, you do not need to use any of Them
     - Is your feature request related to a problem? Please describe.
       A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]
       
     - Describe the solution you'd like
       A clear and concise description of what you want to happen.

     - Describe alternatives you've considered
       A clear and concise description of any alternative solutions or features you've considered.

     - Additional context**
     Add any other context or screenshots about the feature request here. 

    value: 
  validations:
    required: true
- type: dropdown
  id: os
  validations:
    required: false
  attributes:
    label: If this feature is Operating System specific, please select it?
    multiple: true
    options:
      - Windows
      - Mac OS
      - Mac OS X
      - Linux - Red hat
      - Linux - Fedora/Centos/Rocky linux
      - Linux - Ubuntu
      - Linux - other
- type: input
  id: os_other
  attributes:
    label: Other operating system(s)
    description: Operating system(s) not in the options above can be added here
    placeholder: Other OS
- type: textarea
  id: notes
  attributes:
    label: Notes
    description: Is there something else? 
    placeholder: | 
                  Something you want to add?  
                  Please do, I would appreciate it :)
    render: shell
      
     
